
// Functions to help render source modals

import { InteractionSource } from "@/lib/api/types";

export function getSourceColorClass(sourceName: string): string {
  switch (sourceName.toUpperCase()) {
    case 'RXNORM':
      return "bg-blue-100 text-blue-700";
    case 'FDA':
      return "bg-purple-100 text-purple-700";
    case 'FDA ADVERSE EVENTS':
    case 'OPENFDA ADVERSE EVENTS':
      return "bg-red-100 text-red-700";
    case 'SUPP.AI':
      return "bg-green-100 text-green-700";
    case 'AI LITERATURE ANALYSIS':
      return "bg-amber-100 text-amber-700";
    default:
      return "bg-gray-100 text-gray-700";
  }
}

export function getSeverityIcon(severity: string): string {
  switch (severity.toLowerCase()) {
    case 'severe':
      return "XCircle";
    case 'moderate':
      return "AlertTriangle";
    case 'minor':
      return "AlertTriangle";
    case 'unknown':
      return "HelpCircle";
    case 'safe':
      return "CheckCircle";
    default:
      return "HelpCircle";
  }
}

export function getSeverityIconColor(severity: string): string {
  switch (severity.toLowerCase()) {
    case 'severe':
      return "text-red-600";
    case 'moderate':
      return "text-orange-500";
    case 'minor':
      return "text-yellow-500";
    case 'unknown':
      return "text-gray-500";
    case 'safe':
      return "text-green-500";
    default:
      return "text-gray-500";
  }
}

export function getSourceDisclaimer(sourceName: string): string {
  switch (sourceName.toUpperCase()) {
    case 'RXNORM':
      return "RxNorm data reflects standard drug terminology and known interactions from the National Library of Medicine. It may not include all possible interactions or new research.";
    case 'FDA':
    case 'OPENFDA':
      return "Information from FDA drug labels represents approved labeling information. Consult current product labeling for the most up-to-date information.";
    case 'FDA ADVERSE EVENTS':
    case 'OPENFDA ADVERSE EVENTS':
      return "Note: Adverse event reports reflect correlation, not causation. These events are submitted voluntarily and may not confirm a proven interaction.";
    case 'SUPP.AI':
      return "SUPP.AI provides supplement-drug interactions extracted from scientific literature. These interactions may represent emerging evidence and should be verified with clinical judgment.";
    case 'AI LITERATURE ANALYSIS':
      return "This analysis is generated by AI processing of scientific literature. Results should be verified against primary sources and clinical expertise.";
    default:
      return "This data source is one of several analyzed by VitaCheck. Always consult healthcare professionals for medical advice.";
  }
}

export function getSourceContribution(
  sourceData: InteractionSource | undefined,
  eventCount?: number,
  seriousCount?: number
): string {
  if (!sourceData) {
    return "This source contributed to the overall interaction assessment.";
  }
  
  // For adverse events data
  if (eventCount !== undefined && eventCount > 0) {
    const seriousText = seriousCount && seriousCount > 0 
      ? `(including ${seriousCount} serious)` 
      : "";
    
    return `This data source contributed ${eventCount.toLocaleString()} reported cases ${seriousText}, which influenced the final severity rating through VitaCheck's weighted consensus model.`;
  }
  
  // For other sources with confidence scores
  if (sourceData.confidence !== undefined) {
    return `This source contributed to the overall assessment with ${sourceData.confidence}% confidence, influencing the final severity rating through VitaCheck's weighted consensus model.`;
  }
  
  // For sources with defined severity
  if (sourceData.severity) {
    const severityMapping: Record<string, string> = {
      'severe': 'high',
      'moderate': 'moderate',
      'minor': 'low',
      'unknown': 'uncertain',
      'safe': 'minimal'
    };
    
    const riskLevel = severityMapping[sourceData.severity.toLowerCase()] || 'unknown';
    
    return `This source indicated a ${riskLevel} risk level, which influenced the final severity rating through VitaCheck's weighted consensus model.`;
  }
  
  // Default case
  return "This source contributed to the overall interaction assessment through VitaCheck's weighted consensus model.";
}

// Additional utility functions as needed for source modal components
